---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能。Cloud Volumes ONTAP


NOTE: 最新版Cloud Manager也會提供其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager版本資訊"^] 以取得詳細資料。



== 9.5 P11（2020年3月6日）

9.5 P11 for Cloud Volumes ONTAP the Sfor NetApp現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P11["檢視P11修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.5 P10（2020年1月12日）

9.5 P10 for Cloud Volumes ONTAP the Sfor NetApp現在可透過Cloud Manager取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P10["檢視P10修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.5 P9修補程式（2019年11月17日）

適用於NetApp的9.5 P9修補程式版本Cloud Volumes ONTAP 現在可透過Cloud Manager取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P9["檢視P9修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.5 P8修補程式（2019年10月6日）

9.5 P8 for Cloud Volumes ONTAP the Sfor the Sfor the Sfor the Sfor the NOW現已推出。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P8["檢視P8修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.5 p6修補程式（2019年7月16日）

9.5 p6修補程式版本Cloud Volumes ONTAP 的更新版現已推出。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P6["檢視在p6修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。


NOTE: Cloud Manager會提示您升級至ONTAP 特定的更新版本、其中包含Cloud Volumes ONTAP 重要的解決方案。這就是為何您可能會在這些版本說明中發現修補程式版本之間存在落差的原因。我們僅列出Cloud Manager提供給您的修補程式。



== 9.5 P4修補程式（2019年5月16日）

9.5 P4 for Cloud Volumes ONTAP the Sfor the Sfor the Sfor the Sfor the NOW現已推出。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P4["檢視P4修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 支援AWS CGS環境（2019年5月2日）

美國地區現已推出適用於美國地區的S9.5與Cloud Manager 3.6.4 Cloud Volumes ONTAP透過AWS商業雲端服務（C2S）環境提供智慧社群（IC）。您可以在C2S中部署HA配對和單一節點系統。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html["開始使用AWS C2S環境"^]



== 9.5 P3修補程式（2019年4月25日）

9.5 P3版的Cloud Volumes ONTAP 修補程式現已推出。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P3["檢視P3修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.5 P2修補程式（2019年4月10日）

9.5 P2版的Cloud Volumes ONTAP 更新版for the Sfor the Sfor Sfor此修補程式包含錯誤修正、以及新AWS EC2執行個體類型的Flash Cache支援。Cloud Manager會提示您將現有系統升級至此修補程式版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P2["按一下此處以查看P2修補程式中修正的錯誤"^] （需要NetApp支援網站登入）。



=== Flash Cache支援新的EC2執行個體類型

Premium和BYOL授權現在支援下列EC2執行個體類型：

* c5d.4xlarge
* c5d.9xlarge
* r5d.2xlarge


這些執行個體類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 這些儲存設備使用作_Flash Cache。Flash Cache 可透過即時智慧快取來加速資料存取、快取最近讀取的使用者資料和 NetApp 中繼資料。它適用於隨機讀取密集的工作負載、包括資料庫、電子郵件和檔案服務。

所有磁碟區都必須停用壓縮、才能充分發揮 Flash Cache 效能的改善效益。從Cloud Manager建立磁碟區時、您可以選擇「無儲存效率」、也可以先建立磁碟區、然後再建立 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["使用 CLI 停用資料壓縮"^]。


NOTE: 重新開機後的快取重新溫熱功能不支援 Cloud Volumes ONTAP 使用此功能。



== 美國Azure Central區域的HA支援（2019年3月25日）

目前Azure的美國中部地區支援HA配對。

https://cloud.netapp.com/cloud-volumes-global-regions["請參閱支援的Azure地區完整清單"^]。



== 9.5 P1修補程式（2019年3月18日）

9.5 P1版的Cloud Volumes ONTAP 更新版適用於所有組態。Cloud Manager會提示您將現有系統升級至此修補程式版本。

如果您在Azure中已有HA配對、NetApp將會聯絡您、協助您套用P1修補程式版本。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.5P1["按一下此處以查看P1修補程式中修正的錯誤"^] （需要NetApp支援網站登入）。



== 目前Azure中的平台為平台架構（2019年3月18日）Cloud Volumes ONTAP

隨着9.5 P1修補程式的推出、Azure中的HA配對現已普遍推出（GA）。不再需要預覽授權。

GA版本適用於大多數Azure地區、但下列情況除外：

* 美國中部
* 美國中北部
* 美國Gov地區
* 美國西部
* 美國中西部


這些地區的維護作業可防止Cloud Volumes ONTAP 建立不完整的功能、並防止發生容錯移轉。我們計畫在維護完成後立即支援這些區域。

https://cloud.netapp.com/cloud-volumes-global-regions["請參閱完整的支援Azure地區清單"^]。



== AWS和Azure 9.5 GA（2019年2月4日）

AWS和Microsoft Azure（僅適用於Azure中的單一節點系統）現已推出《一般可用度（GA）》版本Cloud Volumes ONTAP 的更新版本。GA版本包含穩定性修正、AWS中的新功能和過時功能、以及系統容量限制的變更。



=== 所有Premium和BYOL組態的容量上限為368TB

目前、所有組態的系統容量上限Cloud Volumes ONTAP 為368TB、包括AWS和Azure中的單一節點和HA。

在某些組態中、磁碟限制會讓您無法單獨使用磁碟、達到368TB容量限制。在這些情況下、您可以達到368TB容量上限 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["將非作用中資料分層至物件儲存設備"^]。例如、Azure中的單一節點系統可以有252 TB的磁碟型容量、因此Azure Blob儲存設備最多可容納16 TB的非使用中資料。

如需磁碟限制的相關資訊、請參閱 link:reference-storage-limits.html["儲存限制"]。



=== 支援AWS中的M5和R5執行個體

目前支援M5和R5系列的多種執行個體類型：Cloud Volumes ONTAP

[cols="4*"]
|===
| 瀏覽 | 標準 | 優質 | BYOL 


| M5.xLarge  a| 
* m5.2xLarge
* R5.xlarge

 a| 
* M5.4xLarge
* r5.2xlarge

 a| 
* M5.xLarge
* m5.2xLarge
* M5.4xLarge
* R5.xlarge
* r5.2xlarge


|===
這些執行個體使用以KVM技術為基礎的Hypervisor。因此、執行個體支援的資料磁碟數量比其他執行個體類型少：單節點系統最多24個資料磁碟、HA配對最多21個資料磁碟。 link:reference-storage-limits.html["瞭解儲存限制"]。

深入瞭解 https://aws.amazon.com/ec2/instance-types/m5/["M5執行個體"^] 和 https://aws.amazon.com/ec2/instance-types/r5/["R5執行個體"^]。



=== 支援AWS中的NetApp Volume Encryption

https://www.netapp.com/us/media/ds-3899.pdf["NetApp Volume Encryption（NVE）"^] 是一項軟體技術、可一次加密一個磁碟區的閒置資料。資料、Snapshot複本和中繼資料都會加密。資料的存取權是由唯一的XTS-AES-256金鑰提供、每個磁碟區一個金鑰。

目前、利用外部金鑰管理伺服器、支援NetApp Volume Encryption。Cloud Volumes ONTAP不支援Onboard Key Manager。您可以在中找到支援的金鑰管理程式 http://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^] 在*關鍵經理*解決方案下。

您需要從CLI設定NetApp Volume Encryption。然後、您可以使用CLI或System Manager在特定磁碟區上啟用加密功能。Cloud Manager不支援從使用者介面及API進行NetApp Volume Encryption。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-encrypting-volumes.html["瞭解如何設定NetApp Volume Encryption"^]


NOTE: NetApp Volume Encryption是一種不同Cloud Volumes ONTAP 於以集合體層級加密資料的功能、現在已不再使用。無法在這兩種加密技術之間進行升級。請參閱 <<Deprecated features in AWS>> 以取得更多資訊。



=== AWS中已過時的功能

9.5版不再支援兩項功能。



==== 目前、支援AWS原生磁碟加密的實體層級加密Cloud Volumes ONTAP

不再支援使用外部金鑰管理程式之集合體的閒置資料加密。如果您目前正在使用此功能並想要升級、則必須先啟動新的9.5系統、然後再啟動 https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html["複寫資料"] 系統。

使用其他方法仍支援閒置資料加密。您可以使用NetApp Volume Encryption或使用AWS金鑰管理服務（KMS）來加密資料。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-security.html["深入瞭解閒置資料的加密"^]。



==== 不再支援c4.2xLarge

9.5版不支援c4.2xLarge執行個體類型。如果您目前使用此執行個體類型、則必須先使用 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["變更為新的執行個體類型"] 升級至9.5版之前。



== 9.5 RC1 for Azure（2018年12月4日）

Microsoft Azure現已推出更新版的RC9.5 RC1。Cloud Volumes ONTAP9.5版將於稍後在AWS中提供。



=== 在Microsoft Azure中預覽高可用度（HA）配對

Microsoft Azure中的「更新版」現已推出更新版本Cloud Volumes ONTAP 。HA配對可在雲端環境發生故障時、提供企業級的可靠性和持續運作。與實體ONTAP 的實體叢集類似、Azure HA配對中的儲存設備會在兩個節點之間共用。

Azure中的HA配對可供預覽。如需預覽授權、請聯絡我們：ng-Cloud-Volume-ONTAP-preview@netapp.com。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["深入瞭解Azure中的HA配對"^]。



=== 提升Azure的網路效能

支援的支援系統Cloud Volumes ONTAP https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli["加速網路"^] 在Azure中。當您升級至9.5版、並部署新的9.5版系統時、Cloud Manager可加速網路連線。



=== 支援新的Azure地區

您現在可以在Cloud Volumes ONTAP 法國中部地區部署這個功能。



=== 支援Azure中的NetApp Volume Encryption

https://www.netapp.com/us/media/ds-3899.pdf["NetApp Volume Encryption（NVE）"^] 是一項軟體技術、可一次加密一個磁碟區的閒置資料。資料、Snapshot複本和中繼資料都會加密。資料的存取權是由唯一的XTS-AES-256金鑰提供、每個磁碟區一個金鑰。

目前、利用外部金鑰管理伺服器、支援NetApp Volume Encryption。Cloud Volumes ONTAP不支援Onboard Key Manager。您可以在中找到支援的金鑰管理程式 http://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^] 在*關鍵經理*解決方案下。

您需要從CLI設定NetApp Volume Encryption。然後、您可以使用CLI或System Manager在特定磁碟區上啟用加密功能。Cloud Manager目前不支援NetApp Volume Encryption。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-encrypting-volumes.html["瞭解如何設定NetApp Volume Encryption"^]



== 升級附註

* 必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.4版升級至S49.5版。
* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

