---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features, ha limitations, nfsv4, nfsv3, data tiering, disks, aggregates 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。



== 一般限制

下列限制適用於Cloud Volumes ONTAP AWS和Azure中的功能。



=== 最大並行複寫作業數

無論執行個體類型或機器類型為何、每個節點的並行SnapMirror或SnapVault 支援Cloud Volumes ONTAP 物件傳輸數量上限為100。



=== 軟體更新必須由Cloud Manager完成

必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。



=== 不得從雲端供應商的主控台修改部署Cloud Volumes ONTAP

從Cloud Volumes ONTAP 雲端供應商的主控台變更支援的支援功能組態、會導致不受支援的組態設定。Cloud Manager所建立及管理的任何更新、都可能影響系統穩定性及Cloud Manager管理系統的能力。Cloud Volumes ONTAP



=== 磁碟和集合體必須從Cloud Manager進行管理

所有磁碟和集合體都必須直接從 Cloud Manager 建立和刪除。您不應從其他管理工具執行這些動作。這樣做可能會影響系統穩定性、阻礙未來新增磁碟的能力、並可能產生備援雲端供應商費用。



=== 不受授權限制SnapManager

支援以伺服器為單位的各個伺服器授權。SnapManager Cloud Volumes ONTAP不SnapManager 支援每個儲存系統（不支援此套件）授權。



=== 不支援ONTAP 的支援功能

下列功能Cloud Volumes ONTAP 不支援使用下列功能：

* Aggregate層級即時重複資料刪除技術
* Aggregate層級背景重複資料刪除技術
* 磁碟維護中心
* 磁碟資料抹除
* 光纖通道（FC）
* Flash資源池
* FlexCache
* 無限Volume
* 介面群組
* 內部網路模式LIF容錯移轉
* MetroCluster
* 多租戶（僅支援一個資料服務SVM）
* RAID4、RAID-DP、RAID-TEC 功能（支援RAID0）
* 服務處理器
* 支援一致性與企業模式（僅支援Cloud WORM）SnapLock
* SnapMirror同步
* VLAN




== AWS的已知限制

下列已知限制會影響Cloud Volumes ONTAP AWS中的功能。



=== Flash Cache限制

C5D和R5D執行個體類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 可做為_Flash Cache。請注意下列限制：

* 所有磁碟區都必須停用壓縮、才能充分發揮 Flash Cache 效能的改善效益。
+
從Cloud Manager建立磁碟區時、您可以選擇「無儲存效率」、也可以先建立磁碟區、然後再建立 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["使用 CLI 停用資料壓縮"^]。

* 重新開機後的快取重新溫熱功能不支援 Cloud Volumes ONTAP 使用此功能。




=== Amazon CloudWatch回報的誤報

由於閒置時無法釋出CPU、因此Amazon CloudWatch可以針對EC2執行個體回報高CPU警告、因為它可以100%使用。Cloud Volumes ONTAP您可以忽略此警報。使用「flex統計 資料」命令可顯示CPU的實際使用量。ONTAP



=== 不支援立即儲存恢復的部分Cloud Volumes ONTAP

節點重新開機後、合作夥伴必須先同步資料、才能退回儲存設備。重新同步資料所需的時間取決於節點當機時用戶端寫入的資料量、以及恢復期間的資料寫入速度。



=== AWS C2S環境的限制

檢視Cloud Manager文件中的限制： https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html["開始使用AWS C2S環境"^]



=== AWS GovCloud（美國）地區的限制

* 如果您想要在Cloud Volumes ONTAP 任何AWS GovCloud（美國）區域中啟動執行個體、Cloud Manager必須部署在AWS GovCloud（美國）區域。
* 當部署於AWS GovCloud（美國）區域時、Cloud Manager無法在ONTAP 適用於Microsoft Azure組態的NetApp私有儲存設備或適用於SoftLayer組態的NetApp私有儲存設備中探索到各種非功能叢集。




=== 不支援中斷EBS磁碟區的連線與重新連線

不Cloud Volumes ONTAP 支援將EBS Volume從一個實例中分離出來、然後將其重新附加到另一個Cloud Volumes ONTAP 實例。您應該使用Cloud Manager在執行個體之間複寫資料。



== Microsoft Azure的已知限制

下列已知限制會影響Cloud Volumes ONTAP Azure中的功能。



=== 不支援新部署

Azure不再支援全新部署Cloud Volumes ONTAP 的支援功能。您需要部署Cloud Volumes ONTAP 才能部署的產品。



=== HA 限制

下列限制會影響Cloud Volumes ONTAP Microsoft Azure中的功能組合：

* 不支援資料分層。
* 不支援 NFSv4 。支援 NFSv3 。
* 某些地區不支援 HA 配對。
+
https://cloud.netapp.com/cloud-volumes-global-regions["請參閱支援的 Azure 地區清單"^]。


